# Generated by Django 5.2.4 on 2025-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
