# Generated by Django 5.2.4 on 2025-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_options_conversation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, default='https://static.vecteezy.com/system/resources/previews/007/296/447/non_2x/user-icon-in-flat-style-person-icon-client-symbol-vector.jpg', null=True, upload_to='chat'),
        ),
    ]
