# Generated by Django 5.2.4 on 2025-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, default='https://tinyurl.com/s7483ay5', null=True, upload_to='chat'),
        ),
    ]
