# Generated by Django 5.2.4 on 2025-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_conversation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, default='chat/user-icon-in-flat-style-person-icon-client-symbol-vector.jpg', null=True, upload_to='chat'),
        ),
    ]
