# Generated by Django 5.2.4 on 2025-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
