# Generated by Django 5.2.4 on 2025-07-16 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('profile', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('bio', models.CharField(blank=True, max_length=350, null=True, verbose_name='Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
