# Generated by Django 5.2.4 on 2025-09-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpaper', verbose_name='Wallpaper'),
        ),
    ]
