name: Django CI

on:
  workflow_dispatch:
  push:
    branches:
      [main, dev]
  pull_request:
    branches:
      [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        NAME: ${{ secrets.DB_NAME }}
        USER2: ${{ secrets.DB_USER }}
        PASSWORD: ${{ secrets.DB_PASSWORD }}
        HOST: ${{ secrets.DB_HOST }}
        PORT: ${{ secrets.DB_PORT }}
      run: |
        echo $HOST
        python backend/manage.py test chat user --noinput --parallel
